### ISSUE TITLE
Themes not working in Ubuntu 18.04 (Gnome)

### ISSUE THREAD

**Issue by sfrench007** [klauscfhq/tusk#106]
Themes do not change when using Ubuntu 18.04 (both snap and .deb versions), only the vertical arrow bars seems to change color. 

 - OS: Ubuntu Bionic 18.04.1, under Gnome 3.28.2, x64
 - Tusk Version: 0.11.0 x64

**Comment by jesusjbr** [comment]
If you are using the new version of evernote web client the themes are still is not supported.
Meanwhile you can switch to the older version and the themes will display fine.
See this: 
https://github.com/klauscfhq/tusk/issues/88#issuecomment-397377296

**Comment by klauscfhq** [comment]
Please see #88
