### ISSUE TITLE
Login is leading me to blank screen

### ISSUE THREAD

**Issue by vinisalazar** [klauscfhq/tusk#116]
**Describe the bug**
Hi, I tried to login and it lead to this screen (screenshot below).

**Expected behavior**
It would lead to the usual login screen.

**Screenshots**
![screenshot from 2018-09-24 11-24-44](https://user-images.githubusercontent.com/17276653/45957997-aff42400-bfec-11e8-9e4c-9b0bd8e081ab.png)

**Technical Info (please complete the following information)**
 - OS: Ubuntu 18.04.1 LTS
 - Tusk Version: latest at time of opening this issue.

**Additional context**
I cannot logout or perform any other actions in the app screen. Although when I click Evernote settings, it opens the page in my browser, showing my account is logged in.

**Comment by vinisalazar** [comment]
I am closing this issue because I solved this by quitting from the Tusk icon in the Ubuntu Toolbar, which logged me out, and when I opened Tusk again, the screen was not there anymore. But, it may be useful to look into it.

**Comment by stel-dare** [comment]
I'm having the same issue you had. I tried what you did but it still didn't work. I even restarted my computer.

**Comment by vinisalazar** [comment]
@stel-dare I would suggest reinstallation.
