### ISSUE TITLE
Themes not working, sidebar stuck in Dark, notes stuck in white

### ISSUE THREAD

**Issue by ripslip** [klauscfhq/tusk#125]
**Describe the bug**
I was in the dark theme, but when I opened the software yesterday the sidebar (Shortcuts,Notes,Notebooks,Shared,Tags,Trash) was in dark theme, but the notes (the notes navigation and whatever note is open) are white. I tried to use hotkeys and view-> to change, but nothing changes. I tried to move to Sepia, since nothing is in sepia currently, but even that doesn't work.

**Expected behavior**
Themes will not change through hotkeys or the view->theme option 

![screenshot from 2018-11-01 07-36-06](https://user-images.githubusercontent.com/44100464/47852735-b2475c00-ddaa-11e8-892e-b9ef7c3eb771.png)

**Technical Info (please complete the following information)**
 - OS: Linux Ubuntu 16.04
 - Tusk Version: 0.11.0

**Comment by anticoncept** [comment]
I have the same issue on Mac OS 10.14 and Tusk 0.11.0

**Comment by derekcline** [comment]
I am experiencing the same issue as well on Mac OS 10.14 and Tusk 0.11.0.

**Comment by HybridGorilla** [comment]
Same issue on Ubuntu 16.04 LTS, Tusk 0.11.0

**Comment by klauscfhq** [comment]
Please see #88
