### ISSUE TITLE
Feature Request: Greater integration of themes

### ISSUE THREAD

**Issue by ZakharH** [klauscfhq/tusk#18]
First off, just wanted to say I love this software and the work you're doing. I was wondering if you could implement a feature where when you change the color theme, the font color gets changed. For example, when I change to the dark theme, the font color is also dark and hard for me to read. It gets a bit annoying having to change the font color everytime and how it resets when i revisit the note/create a new note

**Comment by bozzmob** [comment]
This is resolved right? It seems to work fine now I believe.

**Comment by jlee58** [comment]
Hi there,

As a software engineer, I really like to use editors with dark theme. So I am going to say what you did was really great. Solving the problem of having no way to customize the theme of Evernote.

While there is a problem about the font color in dark/black theme. After I check out the code, I think the problem can be solved with javascript injection. Then we can manipulate the CSS style within the iframe. 

Here is the code I added in `browser.js` (see also: [https://github.com/jlee58/tusk](https://github.com/jlee58/tusk))

```
function setFontColor(color){
  //inject Javascript to set font color
    var content = 'var frame = document.getElementById("en-common-editor-iframe");\
      if (frame){\
      frame.contentWindow.document.getElementById("en-note").style.color = "' + color + '"\}';
    webFrame.executeJavaScript(content);
}

function darkMode() {
  document.documentElement.classList.toggle('dark-mode', config.get('darkMode'));
  config.get('darkMode')?setFontColor('#DDD'):setFontColor('#000');
}
```

After this changed, the Vibrant theme will not work properly. I have no idea what is going wrong, hoping you will fix it. 

Thanks

**Comment by coolfizzin** [comment]
Thank you Tusk devs so much for making such excellent dark themes for Evernote. I'm thrilled that somebody has finally done what Evernote has refused to do for its customers for years.

To join in this discussion: I am using Tusk on Windows and I have the same problem with the font color not changing regardless of the theme, so that it is too dark to read. As a temporary fix, I simply go into the Developer Tools, select the text area, and change the CSS for en-note:
```css
en-note {
     color: #eeeeee;
     }
```
This change remains at least as long as Tusk is open, and it works great.

Thanks again!

**Comment by whitmanschorn** [comment]
@coolfizzin thank you, this is exactly what I was looking for. 

I think we could at least allow for some user setting in addition to theme that sets a default text color on new notes?

**Comment by klauscfhq** [comment]
Feature added on [`bfb835b`](https://github.com/klauscfhq/tusk/commit/bfb835b8339d10e1553c6a5d376d25c29104a477) : )

**Comment by omerasif57** [comment]
![jedi](https://user-images.githubusercontent.com/17876048/39395260-f8d461ba-4af5-11e8-9ea8-ad71875be139.PNG)

**Comment by coolfizzin** [comment]
Thank you very much. It looks great!
