### ISSUE TITLE
Feature Request: Automatic updater or update checker

### ISSUE THREAD

**Issue by kartik0025** [klauscfhq/tusk#29]
I'm a Linux user and I use Tusk as much as I use my browser. It would be great if the developers could put an automatic updater or automatic update checker.

Also, I used to use Evernote client in virtually installed Windows. But now thanks to you developers. Thank you. :)

**Comment by klauscfhq** [comment]
Currently `Electron` doesn't support [Linux](https://electron.atom.io/docs/api/auto-updater/#linux) auto-updates.

After each launch and while running, Tusk checks in the background for any available updates and shortly notifies the user, thus it is very hard to miss a new update : )
