### ISSUE TITLE
Evernote account is not opening on Manjaro (Arch) Linux

### ISSUE THREAD

**Issue by Linux-EverNote** [klauscfhq/tusk#32]
## Description

Tusk not working. Evernote account not opening using Manjaro (Arch) Linux

## Error Message (if any)

No ERROR Message. Display blank.

**Comment by liberodark** [comment]
im on manjaro 17.06 x64 XFCE nad is work great

**Comment by liberodark** [comment]
Please send "inxi -F" you have installed nodejs or atom ?

**Comment by liberodark** [comment]
Please try snap version or AppImage version.
Or update to 0.9.3 on AUR

**Comment by klauscfhq** [comment]
Closing, for now, will reopen if needed in the future.
