### ISSUE TITLE
Request: Dark/Light monochrome Icon variations for Linux

### ISSUE THREAD

**Issue by suberb** [klauscfhq/tusk#33]
Hi guys! Is there a possibility to change completely (too big) or at least toggle tray icon to mono, so it would fit my other icons in Wingpanel? Cheers!

![screenshot from 2017-11-02 21 56 46](https://user-images.githubusercontent.com/24309060/32349876-d56374c2-c018-11e7-8998-91bf70cfdce9.png)

**Comment by klauscfhq** [comment]
The Papirus development team has created a magnificent, full-fledged, cross-distribution icon project/collection, supporting almost every single Linux application, [including Tusk](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/commit/69d065540bfb91e66f99839b179f058c5059a974), with additional fully supported dark and light color variations. More in detail at the [Papirus home on Github](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) : )

**Comment by leighss** [comment]
I use Moca icons
How can I change the **_notification_** icon to a different one (smaller and rounded corners)?

**Comment by klauscfhq** [comment]
The new tray icon will be more polished, smaller and rounded in order to integrate better with almost every Linux desktop environment. The release will be available soon : )

**Comment by leighss** [comment]
Great!
Thanks!
