### ISSUE TITLE
Error: Font color issue with mobile and desktop app dark theme

### ISSUE THREAD

**Issue by Hadesy2k** [klauscfhq/tusk#34]
# Reporting an Issue

## Description
Dark themes are cool and I love it. However, there is one issue with it. The font colors, I chose white color as I cannot see clearly at all with default font color (dark grey) in dark theme. The issue is after I chose white font color, the document become unreadable on mobile as the mobile app color is white.

## Suggestion
My suggestion would be if the user chose dark theme change the default color to white on desktop app without having these changes made on mobile.

**Comment by klauscfhq** [comment]
You can follow the conversation about the issue at #18 : )
