### ISSUE TITLE
Cannot access URLs

### ISSUE THREAD

**Issue by mtruyens** [klauscfhq/tusk#35]
Hi, 
When I click on an embedded link in one of my notes, my main browser (Opera) is invoked, which redirects to Evernote's website, and then results in an error. 

For example, when the note has a link to "www.arstechnica.com", the following URL is opened in Opera:

https://www.evernote.com/OutboundRedirect.action?dest=http%3A%2F%2Fwww.arstechnica.com%2F

which then results in an error.

I am using Linux Mint 18.3, but if I recall correctly, the same behaviour applied in Arch Linux.

**Comment by klauscfhq** [comment]
New release containing the fix will be out soon. Thank you for taking to report it : )
