### ISSUE TITLE
Sidebar is missing.

### ISSUE THREAD

**Issue by etrigan63** [klauscfhq/tusk#39]
## Description
When I open Tusk, the sidebar to the left of the notes is missing. Nothing I do can bring it back.

### Error Message (if any)

```
No error messages
```

## Relevant Links (if any)

No link

## Environment

Tell us which operating system you are using, as well as which versions of [Tusk](https://github.com/klauscfhq/tusk/releases/latest).
Run the following script to get your OS info quickly.

```
OS Type: 	Linux
OS Platform:	linux
OS Release: 	4.13.0-21-generic
Architecture: 	x64

```

## Additional Information

Include any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by andygikling** [comment]
Bump.  
The sidebar is totally missing on my system too.  Any ideas?

No error messages. 
Linux andy-xps 4.14.8-1-ARCH #1 SMP PREEMPT Wed Dec 20 21:27:44 UTC 2017 x86_64 GNU/Linux
Thanks!
Sweet app though!

**Comment by andygikling** [comment]
Bump again.  
The navigation bar on the left is missing in Windows too.
What happened?  We can't make New notes!
Thanks,
~Andy

**Comment by klauscfhq** [comment]
Since version [`0.9.0`](https://github.com/klauscfhq/tusk/releases/tag/v0.9.0) the **`Side Bar`** is by default hidden.
You can toggle it using the **`Toggle Side Bar`** option, residing inside of the **`View`** menu.

![screenshot 3](https://user-images.githubusercontent.com/12670537/34642903-b3a0563c-f323-11e7-9ba6-b7ca43eb492b.png)

**Comment by etrigan63** [comment]
What menu?
![screenshot from 2018-01-06 13 57 41](https://user-images.githubusercontent.com/7347264/34642943-b1c63550-f2e9-11e7-8dd1-d24a458bcf1b.png)

**Comment by klauscfhq** [comment]
You can reveal the app's `Menu Bar` by pressing the `ALT` key once, on both Linux and Windows. 
It is documented in the readme's [`Keyboard Shortcuts` section](https://github.com/klauscfhq/tusk#keyboard-shortcuts).

**Comment by etrigan63** [comment]
Not being a regular denizen of github, I was expecting the help within the app to provide this.

**Comment by andygikling** [comment]
Just a thought - having both the sidebar and top menu bar hidden by default is so unintuitive we actually filed a bug for it here... 
It's pretty anti-pattern for a Windows application to default to not showing the menu bar.

Perhaps a tab on the left side of the screen to fly out the side bar could help new users.
Thanks for this impressive app though!  I love it!

**Comment by klauscfhq** [comment]
Yep, on the upcoming release both features `Menu Bar` and `Side Bar` with be set to `visible` by default, to improve the user experience and increase the app engagement. Thank you for taking the time to share your thoughts : )

**Comment by marianajo** [comment]
[`0.9.2`](https://github.com/klauscfhq/tusk/releases/tag/v0.9.2) is said to have the `Side Bar` set as `Visible` by default but it wasn't visible by default here, neither the `Menu Bar`. I had to follow the instructions on this page in order to see the side bar.
I'm on Ubuntu 17.10 (Artful).
