### ISSUE TITLE
Feature Request:  Short Cut Key for Datetime Stamp

### ISSUE THREAD

**Issue by gopu44** [klauscfhq/tusk#4]
This is one of the most nifty Apps i have ever used !! congrats on this.. this gives me the confidence that web-apps is the way to the future, the lightness in comparison to Native Evernote is just mindblowing..  This is coming from a Nearly 10Y user of Evernote right from its origins and a paid premium user for the past 1.5Y. Hopefully Evernote makes this official and builds a market place platform around their back end service like GOOGLE  

And the way the keyboard has been integrated is key and critical for the success of such an app.. i am very happy to finalyl get a good Evernote Alt for Linux { my windows rusn as a virtualBox/VM inside linux and would like to have Evernote on the linux host.

Specifically, My suggestion is to have a keyboard shortcut for DateTime Stamp that is very useful while taking notes during lectures and meetings where the timestamp { CTRL+;] insert is very nifty to keep track of the points being made, i make notes non -SEQ like a tree of topics / issues and use timestamps to maintain the SEQ 
Keep up the good work god bless 
Thanks Vish

**Comment by klauscfhq** [comment]
Thank you so much for your kind words, we are super happy that you enjoy the app! 🎉 
Also, thank you a lot for taking the time to suggest the feature, it will be available, as soon as possible, on the upcoming release : )

**Comment by gopu44** [comment]
nice of you to respond that quick
of the team can also bring in the Ctrl+d font dialog into the app
[understand it's complex to pull off on a web app] that will be manna

vish

**Comment by sgsen** [comment]
I also wanted to pass on both my support for the app overall as well as add my +1 to the request for shortcuts to insert date and time. 

I have been using evernote for ages. But after switching to Linux a few years ago, I have found the webapp to be a poor substitute for the desktop app I was used to. With Tusk I hardly miss the desktop app. Thanks for that.

**Comment by timoc** [comment]
This is not working for me, as you have a fixed timestamp format mm/yy/dd, which is US only.

Can you make it configurable, or select from a set of options? i for example use date and time  [2018-09-11 09:30] and [2018 w37] because i can sort them properly if they are used in note headlines, and they are easier to search on
