### ISSUE TITLE
Using shortcut keys resets the window location after using "smart window layout"

### ISSUE THREAD

**Issue by Bomadeno** [klauscfhq/tusk#41]
## Description

When you expand the Tusk window to fill Windows (top to bottom) by dragging the top of the Tusk window to hit the top of your screen, the screen correctly expands to fill the height of the window. Likewise if you drag it to the right or left (to fill half the screen), it fills the side of the screen.
If you then create a new note (or use many other keyboard shortcuts) such as ctrl+n, or ctrl+k the window "restores" to it's previous location. This is unexpected behavior. The expected behavior is that the window should stay where you put it.

## Environment

Version 0.9.2 on Windows 10 x64 (fully updated version, 3 feb 2018). 
Run the following script to get your OS info quickly.

## Additional Information

The behavior *is* correct if you click "New Note". The error only occurs when using the keyboard shortcut.

**Comment by klauscfhq** [comment]
Thank you for taking the time to report the issue : )
