### ISSUE TITLE
Issue: Broken Vibrant Themes and Note Title is Cropped on Macos

### ISSUE THREAD

**Issue by Septillion** [klauscfhq/tusk#42]
![2018-02-07 15 21 12](https://user-images.githubusercontent.com/5908006/35903807-ac2eec2c-0c1b-11e8-99bd-4fabb53be7b8.png)

I'm running Tusk with YinXiang in Chinese (simplified) macOS High Sierra. As you can see from the snapshot above, the title bar is not correctly rendered. 

And here's a small advice: According to Apple's design guidelines, Vibrant translucency effect should only be used on sidebars or toolbars, not on the main section of the app. Because Evernote is ultimately a text editor, the main text area should have a solid background to reduce clutter and eye strain.

![2018-02-07 15 31 59](https://user-images.githubusercontent.com/5908006/35903916-13c7c6a6-0c1c-11e8-8b54-a77efbfdfb54.png)

And when using the default white theme, the two big characters "笔记" (which stands for "notes") on the top-left corner is somehow clipped.

Thanks for this awesome Electron port after all.

**Comment by klauscfhq** [comment]
Thank you a lot for the thorough report : )
