### ISSUE TITLE
Issue: Impossible to Select Text on Macos

### ISSUE THREAD

**Issue by Septillion** [klauscfhq/tusk#43]
Because it always triggers a drag action on the window itself.

**Comment by cswarth** [comment]
Duplicate of #37.
Agreed, this is unbelievably annoying.

**Comment by klauscfhq** [comment]
Fixed on [`105953d`](https://github.com/klauscfhq/tusk/commit/105953de8bd435cfd4b4f4bcdb35ee905ee4dc76).

**Comment by wei-chun** [comment]
I have already update the newest version.
When I want to select text, it always drag the windows.
My version: tusk 0.23
My macOS: 10.14.5 Mojave
How can I solve it?

**Comment by nataliastanko** [comment]
It is still unresolved on the mac system
My tusk version: tusk 0.23
My macOS: 10.15.7 Catalina
