### ISSUE TITLE
Issue: "Hide Tray Icon" brakes the app on Manjaro KDE Linux

### ISSUE THREAD

**Issue by michaldybczak** [klauscfhq/tusk#46]
## Description

I'm new to Tusk so I may be wrong but I didn't find any app settings. Clicking on Settings opens Evernote page which is confusing. So the only settings are on right click and one of them is "Hide Tray Icon". I hate useless tray icons and I dislike programs hiding in a tray so I always disable it. I wanted to do that here as well. Usually, there is a proper setting in settings but since there is no such thing here I was left with a bizarre choice: use a tray to disable tray... So I opened the app window, right clicked on "Hide Try Icon" and the tray was gone... along with the window. No way to access the app. I restarted it and... the process is there but again, no way to access the app. Is it an intended behavior? If so, I don't see the point.

I was able to recover from it by deleting Tusk configs but that isn't an elegant fix.

So my issues are:

1. Lack of app settings which makes things more confusing and introduce issues.
2. Setting "Hide Tray Icon" shouldn't hide window, it should do the opposite! A window should become always visible until the app is closed and there should be a way to turn tray on if someone has changed their mind but since there are no app settings...

P.S. I found "Hide Tray Icon" in the menu so I was wrong, there is a way to restore it but not when app window and also menus are not accessible. The baseline is that the setting works incorrectly by hiding window.

## Environment
OS Type:        Linux
OS Platform:    linux
OS Release:     4.15.4-2-MANJARO
Architecture:   x64
DE: Plasma 5.12.1

**Comment by klauscfhq** [comment]
The creation of the tray-icon takes place in the app's startup process, so in order for it to be hidden, the app has to restart and disable its creation, thus leading to a tray-icon-free session. Options to disable/enable the tray-icon are available at the tray-icon menu itself, as well as at main top menubar, which is enabled and visible by default, thus the user is always able to access the options no matter the state of the tray-icon.

Also, I am having trouble to reproduce the issue on both Ubuntu Unity 16.04 and Ubuntu Gnome 18.04. Tusk restarts normally and the tray-icon stays hidden, so it could possibly be an Electron related bug on Manjaro or KDE. I will try to give it go on both and see how it could be resolved.

**Comment by michaldybczak** [comment]
I checked it today and bug is gone. Hiding try icon makes Tusk window disappear but the re-appear. I can set try to be visible from menu then and then the same process of disappear-appear happens. All seems fine.

Some time has passed since I posted this bug and there was many system updates so I guess issue is no more. Things on rolling releases happen very fast ;).
