### ISSUE TITLE
Snapcraft

### ISSUE THREAD

**Issue by liberodark** [klauscfhq/tusk#47]
Hello,

Please add tusk on https://snapcraft.io/ for more simple install and auto building :D 

Cordialy

**Comment by klauscfhq** [comment]
The snap has already been pushed to the store. Awaiting for `classic confinement` to be granted.

More on this at the [snapcraft forum](https://forum.snapcraft.io/t/requesting-classic-confinement-for-tusk/4216).

@popey 🙌

**Comment by klauscfhq** [comment]
The snap is now live under strict confinement `snap install tusk`
