### ISSUE TITLE
Feature Request: Heading styles

### ISSUE THREAD

**Issue by Philiphlop** [klauscfhq/tusk#48]
As #8 has pointed out, Mardown is one of the most requested features of Evernote official. Evernote does have a similar approach by supporting the below, which is a big step in easy formatting, consistency and clean notes.

```
* Bullet
* Bullet

1. Number
1. Number

Ctrl+B Bold

Ctrl+I Italics
```

But it lacks titles support. Either through styles, or shortcut (Ctrl+1, Ctrl+2), or more of a Markdown approach (# Title, ## SubTitle). 

```
Ctrl+1 Heading
Ctrl+2 SubHeading

# Heading
## SubHeading
```

I can live with the already included formatting shortcuts, with an option for H1, H2, H3 headings. Either this or full blown Markdown achieve the "easy to write without messing around with an editor" approach that I like of Markdown, and easy to read in a consistent manner across all notes.

**Comment by klauscfhq** [comment]
Thank you for taking the time to suggest the feature : )
