### ISSUE TITLE
Issue: Continually asks to update

### ISSUE THREAD

**Issue by jamesapdx** [klauscfhq/tusk#50]
Tusk continually asks to update, about every 20 minutes or so, even after I click dismiss.  There does not appear to be a setting to turn this off.  Thanks!

## Environment
Tusk: 0.9.3
OS Type: Linux
OS Platform: Fedora 27
OS Release:  kernel 4.15.4-300.fc27.x86_64
Architecture: x64
DE: Gnome Version 3.26.2

**Comment by jamesapdx** [comment]
Also just noticed clicking the x button on the update alert takes you to the download page, rather than just closing the alert as one would expect.

**Comment by VesterDe** [comment]
I would agree that it would be great to be able to disable update notifications.

I'm using a system repository package for tusk, so I'm dependant on others to update it, and the notification is rather frequent and bothersome at times.

**Comment by Amandaville** [comment]
I agree, the constant pop-ups are beyond ridiculous. No app should ever nag the user that much.  I love the Tusk app but I actually went back to the Evernote web app for a week because of the nagging notifications.  I'm up to date now but dread the next update cycle.  I can't always drop what I'm doing immediately to update an app.

**Comment by klauscfhq** [comment]
New option to manually change the update-checking frequency will be added on the upcoming release. Currently, Tusk checks for available updates every one hour, so it will be possible for the users to switch that to longer time periods.

Also, Linux users on `snap` supported systems are strongly encouraged to install the [official snap package](https://snapcraft.io/tusk) of Tusk directly from their terminal, and have access to automatic, cutting edge updates as soon as they are released on Github : )

**Comment by brandones** [comment]
I have it set to "Daily" and am still being prompted to update many times a day.

**Comment by piedrok** [comment]
PLease add "never" as frequency as well. On Arch Linux I get the updates with the AUR (Arch user repository). 
Clicking on "update" wouldn't work anyway. 

Seriously, I like trying to work with Tusk. But why do you insist on nagging users that do not need nor want this update functionality... it just reminds me once a day to look for a better notetaking solution... 

Thanks for your work and efforts, it is appreciated. 
No need for anymore "in your face" notifications. 

Thx, best regards, pk
