### ISSUE TITLE
Feature request: Global shortucts to create or find a note

### ISSUE THREAD

**Issue by AlexeyKot** [klauscfhq/tusk#54]
It would so great to implement global shortcuts in Tusk. It is very convenient to quickly search for a note with a global hot-key like *Win + Shift + F*, rathen then click on Tusk app and then using Ctrl+F.

Original Evertnote client has following global shortcuts (Windows)

**Shortcut | Action**

Ctrl + Alt + N | New note
Win + Shift + F | Find in Evernote
Win + PrintScreen | Capture screen
Win + A | Copy selection
Ctrl + Alt + V | Paste clipboard

I think the most used are first two ones - create a note and find a note. 

I don't have experience in developing with Electron, but here's what I've quickly found:
[https://github.com/electron/electron/blob/master/docs/api/global-shortcut.md](https://github.com/electron/electron/blob/master/docs/api/global-shortcut.md)

**Comment by klauscfhq** [comment]
Thank you for taking the time to suggest it : )
