### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by amirography** [klauscfhq/tusk#57]
Hello.
I think it would be awesome if you add Right-to-Left formatting. Almost every language in middle-east is written RTL and it basically makes Evernote available to 371 million people using this language. 
[Link to RTL's Wikipedia page](https://en.wikipedia.org/wiki/Right-to-left)

And also, thanks for the robust and amazing work you're doing!

**Comment by dotamir** [comment]
Hi @klauscfhq . I'll work on this feature and will create a pull request when I did that.

**Comment by dotamir** [comment]
@klauscfhq I'm working on it and I'll create a pull request when I did.

**Comment by klauscfhq** [comment]
RTL support added on (#80).
