### ISSUE TITLE
Default shortcut for inserting checkbox also opens inspector

### ISSUE THREAD

**Issue by ankur-gos** [klauscfhq/tusk#59]
## Description

Inserting a checkbox using the default ctrl-shift-c will insert a checkbox correctly, but will also open a developer console (which is also mapped to ctrl-shift-i).

## Environment

Tusk Version: 0.9.4

OS Type: 	Linux
OS Platform:	linux
OS Release: 	4.13.0-37-generic
Architecture: 	x64

## Additional Information

I've remapped the key to get around this.

**Comment by klauscfhq** [comment]
Thank you for taking the time to report it : )
