### ISSUE TITLE
Feature request: implement toggleable hotkey for focus mode

### ISSUE THREAD

**Issue by Barafu** [klauscfhq/tusk#67]
Focus mode is binary. It is either on or off. It is always obvious if Focus mode is on, or not. Thus, different hotkeys to enter and exit focus mode are inconvenient. One Ctrl+K could work both ways, without confusing users. For example, Fullscreen works this way, one F11 works both ways, nobody ever complained. 

Suggestion: make Focus mode hotkey turn Focus mode on if it is off, and off if it is on.

**Comment by klauscfhq** [comment]
Indeed that would be better, as it would fit in nicely with the rest toggleable options, that already share the same logic. Thank you for taking the time to suggest it : )
