### ISSUE TITLE
Grey Font Color [0.10.1] [Windows 7]

### ISSUE THREAD

**Issue by omerasif57** [klauscfhq/tusk#73]
I just installed windows client for the first time. 
Everything works fine but the **paragraph** font in **Dark Theme** is grey. I checked here and there but couldn't find any option to change font color. 
Please advise.

**Comment by klauscfhq** [comment]
The issue has fixed on [`bfb835b`](https://github.com/klauscfhq/tusk/commit/bfb835b8339d10e1553c6a5d376d25c29104a477). The original issue thread is #18.
New release delivering the fix will be out later today : )

**Comment by omerasif57** [comment]
sounds great!
