### ISSUE TITLE
Chinese cannot input correctly

### ISSUE THREAD

**Issue by paolo-dai** [klauscfhq/tusk#75]
## Description
![image](https://user-images.githubusercontent.com/4970600/39435534-457b06a2-4cce-11e8-8d44-2ed077dd487a.png)
As the image shows above, when i type string "nizhende", the input application only catch "nizhene" and the char "d" was forward to Tusk. I tried sevral input capplications including Google拼音(Chinese input of Google) , Sougou and Sunpinyin, none of them works correct along with Tusk. Actually, the same problem shows when using another application which is Mailspring.

## Relevant Links (if any)
https://github.com/klauscfhq/tusk/issues/58

## Environment
OS Type: 	Linux
OS Platform:	linux
OS Release: 	4.4.0-121-generic
Architecture: 	x64
Ubuntu 16.04.4 LTS \n \l

**Comment by klauscfhq** [comment]
Please track #58 for updates on this issue.
